/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface_meatAdmin;

import db4util.Db4util;
import ecosystem.Ecosystem;
import user_interface_foodAdmin.*;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import organisation.FoodVendorOnboarding;
import organisation.MeatVendorDirectory;
import organisation.MeatVendorOnboarding;
import user_interface.MainJFrame;
import static user_interface_foodAdmin.foodAdminMainPanel.foodShopTable;
import static user_interface_foodAdmin.foodAdminMainPanel.index;

/**
 *
 * @author snehagovindarajan
 */
public class meatAdminMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form foodAdminMainPanel
     */
    Ecosystem system;
    MainJFrame mainframe;
    public static int index = 99;
     MeatVendorDirectory meatShopList;
     int shopIndex;
    //DefaultTableModel tblmodel;
    private Db4util dB4OUtil = Db4util.getInstance();
    public meatAdminMainPanel(Ecosystem system,MainJFrame mainframe) {
        initComponents();
        
        ItemsContainer.setBackground(new Color(0,0,0,90));
        this.system = system;
        this.mainframe = mainframe;
         meatShopList = system.getMeatDirectory();
         populateMeatShopTable();
    }
    
        private void populateMeatShopTable() {
       DefaultTableModel model = (DefaultTableModel) meattable.getModel();
        model.setRowCount(0);
        for(int i=0; i< meatShopList.getMeatVendorList().size(); i++)
        {
             Object data_value [] = {meatShopList.getMeatVendorList().get(i).getShop_id(),
                 
                 meatShopList.getMeatVendorList().get(i).getShop_name(),
                 
                 meatShopList.getMeatVendorList().get(i).getLocation()

            };
           model.addRow(data_value);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemsContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        meattable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        meatShopName = new javax.swing.JTextField();
        locationMeat = new javax.swing.JTextField();
        meatShopDeleteBtn = new javax.swing.JButton();
        meatUpdateShop = new javax.swing.JButton();
        clearMeatShop = new javax.swing.JButton();
        addMeatShop = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        temp = new javax.swing.JPanel();
        meatAdminImage = new javax.swing.JLabel();

        setLayout(null);

        meattable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shop Id", "Shop Name", "Location"
            }
        ));
        meattable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meattableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(meattable);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Shop Name");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Location");

        meatShopName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatShopNameActionPerformed(evt);
            }
        });

        meatShopDeleteBtn.setText("Delete Shop");
        meatShopDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatShopDeleteBtnActionPerformed(evt);
            }
        });

        meatUpdateShop.setText("Update Shop");
        meatUpdateShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatUpdateShopActionPerformed(evt);
            }
        });

        clearMeatShop.setText("Clear");
        clearMeatShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMeatShopActionPerformed(evt);
            }
        });

        addMeatShop.setText("Add Shop");
        addMeatShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMeatShopActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lao MN", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Add Food Shops");

        javax.swing.GroupLayout ItemsContainerLayout = new javax.swing.GroupLayout(ItemsContainer);
        ItemsContainer.setLayout(ItemsContainerLayout);
        ItemsContainerLayout.setHorizontalGroup(
            ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsContainerLayout.createSequentialGroup()
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemsContainerLayout.createSequentialGroup()
                        .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ItemsContainerLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(addMeatShop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(meatUpdateShop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(meatShopDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(clearMeatShop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(locationMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(meatShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ItemsContainerLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ItemsContainerLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        ItemsContainerLayout.setVerticalGroup(
            ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsContainerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meatShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMeatShop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meatUpdateShop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meatShopDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearMeatShop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );

        add(ItemsContainer);
        ItemsContainer.setBounds(0, 0, 950, 720);

        temp.setLayout(new java.awt.CardLayout());
        add(temp);
        temp.setBounds(0, 0, 0, 0);

        meatAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MeatAdmin.png"))); // NOI18N
        add(meatAdminImage);
        meatAdminImage.setBounds(0, 0, 1200, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void meatShopNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatShopNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meatShopNameActionPerformed

    private void meattableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meattableMouseClicked
        // TODO add your handling code here:
          this.index = meattable.getSelectedRow();
          
         // manageMeatItems.shopName.setText(meatShopList.getMeatVendorList().get(index).getShop_name());
          TableModel model = meattable.getModel();
        meatShopName.setText(model.getValueAt(index, 1).toString());
        locationMeat.setText(model.getValueAt(index, 2).toString());
    }//GEN-LAST:event_meattableMouseClicked

    private void addMeatShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMeatShopActionPerformed
        // TODO add your handling code here:
        if(meatShopName.getText().trim().equals("") || locationMeat.getText().trim().equals("")){
            JOptionPane.showMessageDialog(new JFrame(),
                "Please Enter valid Inputs",
                "Error",
        JOptionPane.ERROR_MESSAGE);
        }else{
        meatShopList = system.getMeatDirectory();

        MeatVendorOnboarding meatShop = meatShopList.createShopData(meatShopName.getText(), locationMeat.getText());
        meatShopList.setMeatVendorList(meatShop); 
        populateMeatShopTable();
         
        JOptionPane.showMessageDialog(new JFrame(), "Meat Admins Added successfully ..!!");
        meatShopName.setText("");
        locationMeat.setText("");
        }
    }//GEN-LAST:event_addMeatShopActionPerformed

    private void meatUpdateShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatUpdateShopActionPerformed
        // TODO add your handling code here:
          shopIndex = meattable.getSelectedRow();
         if (shopIndex < 0 )
        {
                    JOptionPane.showMessageDialog(new JFrame(),
                "Please make a selection",
                "Error",
        JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
        
               // TODO add your handling code here:
      
        String name = meatShopName.getText();
        String location = locationMeat.getText();
        
         meatShopList.getMeatVendorList().get(shopIndex).setShop_name(name);
         meatShopList.getMeatVendorList().get(shopIndex).setLocation(location);
         populateMeatShopTable();
         

       // renderPatient(patientList);
        JOptionPane.showMessageDialog(new JFrame(), "Admins Updated successfully ..!!");
        meatShopName.setText("");
        locationMeat.setText("");

        }
    }//GEN-LAST:event_meatUpdateShopActionPerformed

    private void clearMeatShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMeatShopActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(new JFrame(), "Data Cleared successfully ..!!");
        meatShopName.setText("");
        locationMeat.setText("");
    }//GEN-LAST:event_clearMeatShopActionPerformed

    private void meatShopDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatShopDeleteBtnActionPerformed
        // TODO add your handling code here:
        shopIndex = meattable.getSelectedRow();
//ArrayList<Patient> patientList = patient.getPatientList();
            if (shopIndex < 0 )
        {
                    JOptionPane.showMessageDialog(new JFrame(),
                "Please make a selection",
                "Error",
        JOptionPane.ERROR_MESSAGE);
        }else{
        meatShopList.getMeatVendorList().remove(shopIndex);
        //emp_dir_ob.getEmpAccountList().remove(employeeIndex);
        populateMeatShopTable();
        JOptionPane.showMessageDialog(new JFrame(), "Meat Shop deleted successfully ..!!");
        meatShopName.setText("");
        locationMeat.setText("");
        }
        
    }//GEN-LAST:event_meatShopDeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ItemsContainer;
    private javax.swing.JButton addMeatShop;
    private javax.swing.JButton clearMeatShop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField locationMeat;
    private javax.swing.JLabel meatAdminImage;
    private javax.swing.JButton meatShopDeleteBtn;
    private javax.swing.JTextField meatShopName;
    private javax.swing.JButton meatUpdateShop;
    public static javax.swing.JTable meattable;
    private javax.swing.JPanel temp;
    // End of variables declaration//GEN-END:variables
}
