/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface_foodAdmin;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author snehagovindarajan
 */
public class foodAdminMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form foodAdminMainPanel
     */
    public foodAdminMainPanel() {
        initComponents();
      
        ItemsContainer.setBackground(new Color(0,0,0,90));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemsContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodShopTable = new javax.swing.JTable();
        foodShopName = new javax.swing.JLabel();
        foodShopLocation = new javax.swing.JLabel();
        foodShopNameText = new javax.swing.JTextField();
        foodShopLocationText = new javax.swing.JTextField();
        deleteFoodItemsBtn = new javax.swing.JButton();
        updateFoodItemsBtn = new javax.swing.JButton();
        clearFoodItemsBtn = new javax.swing.JButton();
        manageFoodItemsBtn = new javax.swing.JButton();
        addFoodItemsBtn = new javax.swing.JButton();
        foodContainer = new javax.swing.JPanel();
        foodAdminImage = new javax.swing.JLabel();

        setLayout(null);

        foodShopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shop Id", "Shop Name", "Location"
            }
        ));
        jScrollPane2.setViewportView(foodShopTable);

        foodShopName.setBackground(new java.awt.Color(255, 255, 255));
        foodShopName.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopName.setForeground(new java.awt.Color(255, 255, 255));
        foodShopName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopName.setText("Shop Name");

        foodShopLocation.setBackground(new java.awt.Color(255, 255, 255));
        foodShopLocation.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopLocation.setForeground(new java.awt.Color(255, 255, 255));
        foodShopLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopLocation.setText("Location");

        foodShopNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodShopNameTextActionPerformed(evt);
            }
        });

        deleteFoodItemsBtn.setText("Delete Shop");

        updateFoodItemsBtn.setText("Update Shop");

        clearFoodItemsBtn.setText("Clear");

        manageFoodItemsBtn.setText("Manage Items");
        manageFoodItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFoodItemsBtnActionPerformed(evt);
            }
        });

        addFoodItemsBtn.setText("Add Shop");

        javax.swing.GroupLayout ItemsContainerLayout = new javax.swing.GroupLayout(ItemsContainer);
        ItemsContainer.setLayout(ItemsContainerLayout);
        ItemsContainerLayout.setHorizontalGroup(
            ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsContainerLayout.createSequentialGroup()
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemsContainerLayout.createSequentialGroup()
                        .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ItemsContainerLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(foodShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(foodShopLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(manageFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(foodShopNameText)
                                    .addComponent(foodShopLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(updateFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(deleteFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(clearFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ItemsContainerLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        ItemsContainerLayout.setVerticalGroup(
            ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsContainerLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foodShopNameText)
                    .addComponent(foodShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodShopLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodShopLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(185, 185, 185)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        add(ItemsContainer);
        ItemsContainer.setBounds(0, 0, 1200, 720);

        foodContainer.setLayout(new java.awt.CardLayout());
        add(foodContainer);
        foodContainer.setBounds(0, 0, 0, 0);

        foodAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foodAdmin.png"))); // NOI18N
        add(foodAdminImage);
        foodAdminImage.setBounds(0, 0, 1200, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void foodShopNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodShopNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodShopNameTextActionPerformed

    private void manageFoodItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFoodItemsBtnActionPerformed
        // TODO add your handling code here:
        manageItems foodItemList = new manageItems();
        
        foodContainer.add("foodArea",foodItemList);
        CardLayout layout = (CardLayout) foodContainer.getLayout();
        layout.next(foodContainer);
        ItemsContainer.setVisible(false);
        foodContainer.setVisible(true);
       
    }//GEN-LAST:event_manageFoodItemsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ItemsContainer;
    private javax.swing.JButton addFoodItemsBtn;
    private javax.swing.JButton clearFoodItemsBtn;
    private javax.swing.JButton deleteFoodItemsBtn;
    private javax.swing.JLabel foodAdminImage;
    private javax.swing.JPanel foodContainer;
    private javax.swing.JLabel foodShopLocation;
    private javax.swing.JTextField foodShopLocationText;
    private javax.swing.JLabel foodShopName;
    private javax.swing.JTextField foodShopNameText;
    private javax.swing.JTable foodShopTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton manageFoodItemsBtn;
    private javax.swing.JButton updateFoodItemsBtn;
    // End of variables declaration//GEN-END:variables
}
