/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface_foodAdmin;

import customer.Customer;
import db4util.Db4util;
import ecosystem.Ecosystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import organisation.FoodVendorDirectory;
import organisation.FoodVendorOnboarding;
import user_interface.MainJFrame;

/**
 *
 * @author snehagovindarajan
 */
public class foodAdminMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form foodAdminMainPanel
     */
    
    FoodVendorDirectory fvd;
    Ecosystem system;
    MainJFrame mainframe;
    public static int index = 99;
    DefaultTableModel tblmodel;

    private Db4util dB4OUtil = Db4util.getInstance();

    public foodAdminMainPanel(Ecosystem system, MainJFrame mainframe) {
        initComponents();
        fvd = system.getFoodDirectory();
         tblmodel = (DefaultTableModel)foodShopTable.getModel();
      
         for(int i=0; i< fvd.getFoodVendorList().size(); i++)
        {
             Object data_value [] = {fvd.getFoodVendorList().get(i).getShop_id(),
                 
                 fvd.getFoodVendorList().get(i).getShop_name(),
                 
                 fvd.getFoodVendorList().get(i).getLocation()

            };
           tblmodel.addRow(data_value);
        }

        this.system = system;
        this.mainframe = mainframe;
                
      
        ItemsContainer.setBackground(new Color(0,0,0,90));
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemsContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodShopTable = new javax.swing.JTable();
        foodShopName = new javax.swing.JLabel();
        foodShopLocation = new javax.swing.JLabel();
        foodShopNameText = new javax.swing.JTextField();
        foodShopLocationText = new javax.swing.JTextField();
        deleteFoodItemsBtn = new javax.swing.JButton();
        updateFoodItemsBtn = new javax.swing.JButton();
        clearFoodItemsBtn = new javax.swing.JButton();
        addFoodItemsBtn = new javax.swing.JButton();
        foodContainer = new javax.swing.JPanel();
        foodAdminImage = new javax.swing.JLabel();

        setLayout(null);

        foodShopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shop ID", "Shop Name", "Location"
            }
        ));
        foodShopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodShopTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(foodShopTable);

        foodShopName.setBackground(new java.awt.Color(255, 255, 255));
        foodShopName.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopName.setForeground(new java.awt.Color(255, 255, 255));
        foodShopName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopName.setText("Shop Name");

        foodShopLocation.setBackground(new java.awt.Color(255, 255, 255));
        foodShopLocation.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopLocation.setForeground(new java.awt.Color(255, 255, 255));
        foodShopLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopLocation.setText("Location");

        foodShopNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodShopNameTextActionPerformed(evt);
            }
        });

        deleteFoodItemsBtn.setText("Delete Shop");

        updateFoodItemsBtn.setText("Update Shop");
        updateFoodItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFoodItemsBtnActionPerformed(evt);
            }
        });

        clearFoodItemsBtn.setText("Clear");

        addFoodItemsBtn.setText("Add Shop");
        addFoodItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodItemsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ItemsContainerLayout = new javax.swing.GroupLayout(ItemsContainer);
        ItemsContainer.setLayout(ItemsContainerLayout);
        ItemsContainerLayout.setHorizontalGroup(
            ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsContainerLayout.createSequentialGroup()
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemsContainerLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(foodShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(foodShopLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(foodShopNameText)
                                    .addComponent(foodShopLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ItemsContainerLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(updateFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(deleteFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(clearFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ItemsContainerLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        ItemsContainerLayout.setVerticalGroup(
            ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsContainerLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foodShopNameText)
                    .addComponent(foodShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodShopLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodShopLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(185, 185, 185)
                .addGroup(ItemsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFoodItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        add(ItemsContainer);
        ItemsContainer.setBounds(0, 0, 1200, 720);

        foodContainer.setLayout(new java.awt.CardLayout());
        add(foodContainer);
        foodContainer.setBounds(0, 0, 0, 0);

        foodAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foodAdmin.png"))); // NOI18N
        add(foodAdminImage);
        foodAdminImage.setBounds(0, 0, 1200, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void foodShopNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodShopNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodShopNameTextActionPerformed

    private void addFoodItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodItemsBtnActionPerformed
        // TODO add your handling code here:
        fvd = system.getFoodDirectory();

        FoodVendorOnboarding fv = fvd.createShopData(foodShopNameText.getText(), foodShopLocationText.getText());
        fvd.setFoodVendorList(fv); 
        Object data_value [] = {fv.getShop_id(),
            foodShopNameText.getText(),foodShopLocationText.getText()
                 
                 
            };
           tblmodel.addRow(data_value);
         
       JOptionPane.showMessageDialog(new JFrame(), "Shop Saved succesfully");

        
        
    }//GEN-LAST:event_addFoodItemsBtnActionPerformed

    private void foodShopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodShopTableMouseClicked
        // TODO add your handling code here:
        
        
        this.index = foodShopTable.getSelectedRow();
          TableModel model = foodShopTable.getModel();
//        String shop_name = model.getValueAt(index, 1).toString();
//        String shop_location = model.getValueAt(index, 2).toString();
        
        foodShopNameText.setText(model.getValueAt(index, 1).toString());
        foodShopLocationText.setText(model.getValueAt(index, 2).toString());
    }//GEN-LAST:event_foodShopTableMouseClicked

    private void updateFoodItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFoodItemsBtnActionPerformed
        // TODO add your handling code here:
        
        if (index == 99)
        {
                    JOptionPane.showMessageDialog(new JFrame(),
                "Please make a selection",
                "Error",
        JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
        
        String shopname_edit = foodShopName.getText();
        String shop_loc_edit = foodShopLocation.getText();
        
        
        fvd.getFoodVendorList().get(index).setShop_name(shopname_edit);
        fvd.getFoodVendorList().get(index).setLocation(shop_loc_edit);


        }
        


        
        
    }//GEN-LAST:event_updateFoodItemsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ItemsContainer;
    private javax.swing.JButton addFoodItemsBtn;
    private javax.swing.JButton clearFoodItemsBtn;
    private javax.swing.JButton deleteFoodItemsBtn;
    private javax.swing.JLabel foodAdminImage;
    private javax.swing.JPanel foodContainer;
    private javax.swing.JLabel foodShopLocation;
    private javax.swing.JTextField foodShopLocationText;
    private javax.swing.JLabel foodShopName;
    private javax.swing.JTextField foodShopNameText;
    public static javax.swing.JTable foodShopTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton updateFoodItemsBtn;
    // End of variables declaration//GEN-END:variables
}
