/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface_foodAdmin;
import db4util.Db4util;
import ecosystem.Ecosystem;
import items.ItemDirectory;
import user_interface.MainJFrame;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import organisation.FoodVendorOnboarding;
import user_interface_foodAdmin.foodAdminMainPanel;
import items.Item;
import javax.swing.JTable;
//import static user_interface_foodAdmin.foodAdminMainPanel.foodShopTable;
/**
 *
 * @author snehagovindarajan
 */


public class manageItems extends javax.swing.JPanel {
    Ecosystem system;
    MainJFrame mainframe;
    ItemDirectory id;
    DefaultTableModel tblmodel;
    DefaultTableModel tblmodel1;


    
    private Db4util dB4OUtil = Db4util.getInstance();


    /**
     * Creates new form foodAdminMainPanel
     */
    
    public manageItems(Ecosystem system, MainJFrame mainframe) {
        initComponents();
        tblmodel1 = (DefaultTableModel) foodAdminMainPanel.foodShopTable.getModel();
        


        
        if(foodAdminMainPanel.index !=99)
        {
        String name = tblmodel1.getValueAt(foodAdminMainPanel.index, 1).toString();
        jLabel2.setText(name);
        }
        
        
        
        
        id = system.getItemDirectory();
        

         tblmodel = (DefaultTableModel)meatItemTbl.getModel();
        

         for(int i=0; i< id.getItemList().size(); i++)
        {
             Object data_value [] = {
                 id.getItemList().get(i).getItemName(),
                 id.getItemList().get(i).getPrice(),
                 id.getItemList().get(i).getType(),
                 id.getItemList().get(i).getQuantity()
            };
           tblmodel.addRow(data_value);
        }
        this.system = system;
        this.mainframe = mainframe;
        foodAdminTemp.setBackground(new Color(0,0,0,90));
        //jLabel2.setVisible(true);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        foodAdminTemp = new javax.swing.JPanel();
        foodShopName = new javax.swing.JLabel();
        foodShopName1 = new javax.swing.JLabel();
        foodShopName2 = new javax.swing.JLabel();
        foodShopName3 = new javax.swing.JLabel();
        foodShopName4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        uploadFoodPic = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        meatItemTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        foodShopName.setBackground(new java.awt.Color(255, 255, 255));
        foodShopName.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopName.setForeground(new java.awt.Color(255, 255, 255));
        foodShopName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopName.setText("Upload Image");

        foodShopName1.setBackground(new java.awt.Color(255, 255, 255));
        foodShopName1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopName1.setForeground(new java.awt.Color(255, 255, 255));
        foodShopName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopName1.setText("Type");

        foodShopName2.setBackground(new java.awt.Color(255, 255, 255));
        foodShopName2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopName2.setForeground(new java.awt.Color(255, 255, 255));
        foodShopName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopName2.setText("Quantity");

        foodShopName3.setBackground(new java.awt.Color(255, 255, 255));
        foodShopName3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopName3.setForeground(new java.awt.Color(255, 255, 255));
        foodShopName3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopName3.setText("Item");

        foodShopName4.setBackground(new java.awt.Color(255, 255, 255));
        foodShopName4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        foodShopName4.setForeground(new java.awt.Color(255, 255, 255));
        foodShopName4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        foodShopName4.setText("Price");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veg", "Non Veg"}));

        uploadFoodPic.setText("UPLOAD");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Shop Name");

        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Item");

        jButton3.setText("Delete Item");

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        meatItemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Price", "Type", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(meatItemTbl);

        javax.swing.GroupLayout foodAdminTempLayout = new javax.swing.GroupLayout(foodAdminTemp);
        foodAdminTemp.setLayout(foodAdminTempLayout);
        foodAdminTempLayout.setHorizontalGroup(
            foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodAdminTempLayout.createSequentialGroup()
                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(foodAdminTempLayout.createSequentialGroup()
                        .addGap(0, 88, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(foodAdminTempLayout.createSequentialGroup()
                        .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(foodAdminTempLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(foodShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foodShopName4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foodShopName3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foodShopName1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foodShopName2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62))
                            .addGroup(foodAdminTempLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(foodAdminTempLayout.createSequentialGroup()
                                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(uploadFoodPic, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)
                                .addComponent(jButton4)))))
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(foodAdminTempLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        foodAdminTempLayout.setVerticalGroup(
            foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodAdminTempLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodShopName3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodShopName4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodShopName1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodShopName2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadFoodPic))
                .addGap(30, 30, 30)
                .addGroup(foodAdminTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        add(foodAdminTemp);
        foodAdminTemp.setBounds(0, 0, 1200, 720);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foodAdmin.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Index" + foodAdminMainPanel.index);

        
        id = system.getItemDirectory();
        Item i = id.createItems(jTextField3.getText() , Float.parseFloat(jTextField2.getText()),
                jComboBox1.getSelectedItem().toString(), Integer.parseInt(jTextField4.getText()),
                tblmodel1.getValueAt(foodAdminMainPanel.index, 1).toString()
                );
        id.setItemList(i); 
        Object data_value [] = {
                 jTextField3.getText() , Float.parseFloat(jTextField2.getText()),
                jComboBox1.getSelectedItem().toString(), Integer.parseInt(jTextField4.getText())
                 
            };
           tblmodel.addRow(data_value);
         
       JOptionPane.showMessageDialog(new JFrame(), "Item Saved succesfully");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel foodAdminTemp;
    private javax.swing.JLabel foodShopName;
    private javax.swing.JLabel foodShopName1;
    private javax.swing.JLabel foodShopName2;
    private javax.swing.JLabel foodShopName3;
    private javax.swing.JLabel foodShopName4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable meatItemTbl;
    private javax.swing.JButton uploadFoodPic;
    // End of variables declaration//GEN-END:variables
}
