/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface.customer;
import db4util.Db4util;
import ecosystem.Ecosystem;
import user_interface.MainJFrame;
import customer.Customer;
import cart.Cart;
import cart.CartDirectory;
import order.OrderDirectory;

/**
 *
 * @author nishu
 */
public class CustomerMainPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form NewJPanel
     */
    
    Ecosystem system;
    MainJFrame mainframe;
    CartDirectory crd;
    CartDirectory dcrd;
    OrderDirectory ord;
    private Db4util dB4OUtil = Db4util.getInstance();
    static String cust_id;
    
    public CustomerMainPanel(Ecosystem system, MainJFrame mainframe, Customer cust_ob
    ) {
        initComponents();
        this.system = system;
        this.mainframe = mainframe;
        lblName.setText(cust_ob.getCustomer_name());
        cust_id = cust_ob.getCust_id();
        crd = new CartDirectory();
        dcrd = system.getCartDirectory();
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnFood = new javax.swing.JButton();
        btnGrocery = new javax.swing.JButton();
        btnMeat = new javax.swing.JButton();
        btnPharma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnCart = new javax.swing.JButton();
        btnPastOrders = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        splitPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        splitPane.setDividerLocation(150);
        splitPane.setDividerSize(2);
        splitPane.setPreferredSize(new java.awt.Dimension(200, 23));

        controlPanel.setBackground(new java.awt.Color(153, 153, 153));

        btnFood.setBackground(new java.awt.Color(0, 0, 0));
        btnFood.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFood.setForeground(new java.awt.Color(255, 255, 255));
        btnFood.setText("Food");
        btnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodActionPerformed(evt);
            }
        });

        btnGrocery.setBackground(new java.awt.Color(0, 0, 0));
        btnGrocery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGrocery.setForeground(new java.awt.Color(255, 255, 255));
        btnGrocery.setText("Grocery");
        btnGrocery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroceryActionPerformed(evt);
            }
        });

        btnMeat.setBackground(new java.awt.Color(0, 0, 0));
        btnMeat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMeat.setForeground(new java.awt.Color(255, 255, 255));
        btnMeat.setText("Meat");
        btnMeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeatActionPerformed(evt);
            }
        });

        btnPharma.setBackground(new java.awt.Color(0, 0, 0));
        btnPharma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPharma.setForeground(new java.awt.Color(255, 255, 255));
        btnPharma.setText("Pharma");
        btnPharma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-icon.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Welcome");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("value");

        btnCart.setBackground(new java.awt.Color(0, 0, 0));
        btnCart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCart.setForeground(new java.awt.Color(255, 255, 255));
        btnCart.setText("My Cart");
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });

        btnPastOrders.setBackground(new java.awt.Color(0, 0, 0));
        btnPastOrders.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPastOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnPastOrders.setText("Past Orders");
        btnPastOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastOrdersActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrocery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPharma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPastOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addGap(26, 26, 26)
                .addComponent(btnFood)
                .addGap(27, 27, 27)
                .addComponent(btnGrocery)
                .addGap(26, 26, 26)
                .addComponent(btnMeat)
                .addGap(26, 26, 26)
                .addComponent(btnPharma)
                .addGap(27, 27, 27)
                .addComponent(btnCart)
                .addGap(93, 93, 93)
                .addComponent(btnPastOrders)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop-bg.jpg"))); // NOI18N

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
            .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(workAreaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
            .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(workAreaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodActionPerformed
        // TODO add your handling code here:
        ShopListPanel foodListPanel = new ShopListPanel(system, "food", crd);
        splitPane.setRightComponent(foodListPanel);
    }//GEN-LAST:event_btnFoodActionPerformed

    private void btnGroceryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroceryActionPerformed
        // TODO add your handling code here:
        ShopListPanel groceryListPanel = new ShopListPanel(system, "grocery", crd);
        splitPane.setRightComponent(groceryListPanel);
    }//GEN-LAST:event_btnGroceryActionPerformed

    private void btnMeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeatActionPerformed
        // TODO add your handling code here:
        ShopListPanel meatListPanel = new ShopListPanel(system, "meat", crd);
        splitPane.setRightComponent(meatListPanel);
    }//GEN-LAST:event_btnMeatActionPerformed

    private void btnPharmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmaActionPerformed
        // TODO add your handling code here:
        ShopListPanel pharmaListPanel = new ShopListPanel(system, "pharma", crd);
        splitPane.setRightComponent(pharmaListPanel);
    }//GEN-LAST:event_btnPharmaActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // TODO add your handling code here:
        CartItemsPanel cart = new CartItemsPanel(system, crd, ord);
        splitPane.setRightComponent(cart);
    }//GEN-LAST:event_btnCartActionPerformed

    private void btnPastOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastOrdersActionPerformed
        // TODO add your handling code here:
        PastOrdersPanel pastOrders = new PastOrdersPanel(system, ord, cust_id);
        splitPane.setRightComponent(pastOrders);
    }//GEN-LAST:event_btnPastOrdersActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        CustomerProfilePanel customerProfile = new CustomerProfilePanel();
        splitPane.setRightComponent(customerProfile);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
     mainframe.logoutAction();
     mainframe.displayPane();
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnFood;
    private javax.swing.JButton btnGrocery;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMeat;
    private javax.swing.JButton btnPastOrders;
    private javax.swing.JButton btnPharma;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
