/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface.customer;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author nishu
 */
public class PastOrdersPanel extends javax.swing.JPanel {

    /**
     * Creates new form PastOrdersPanel
     */
    public PastOrdersPanel() {
        initComponents();
        reasonDropDown = new javax.swing.JComboBox<>();
        jPanel1.setBackground(new Color(0,0,0,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPastOrders = new javax.swing.JTable();
        btnCancelOrder = new javax.swing.JButton();
        btnRaiseIssue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        tblPastOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Items", "Price", "Date", "Status"
            }
        ));
        tblPastOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPastOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPastOrders);

        btnCancelOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        btnRaiseIssue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRaiseIssue.setText("Raise Issue");
        btnRaiseIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseIssueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelOrder)
                .addGap(52, 52, 52)
                .addComponent(btnRaiseIssue)
                .addGap(210, 210, 210))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelOrder)
                    .addComponent(btnRaiseIssue))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1040, 710);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop-bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1042, 714);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPastOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPastOrdersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPastOrdersMouseClicked

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnRaiseIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseIssueActionPerformed
        // TODO add your handling code here:
        String message = "Select Reason\n";
        reasonDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Food Quality", "Order Not Delivered", "Item Missing" }));
        Object[] params = {message, reasonDropDown};
        JOptionPane.showConfirmDialog(null, params, "Raise Issue", JOptionPane.PLAIN_MESSAGE);
        String reason = reasonDropDown.getSelectedItem().toString();
    }//GEN-LAST:event_btnRaiseIssueActionPerformed


    private javax.swing.JComboBox<String> reasonDropDown;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnRaiseIssue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPastOrders;
    // End of variables declaration//GEN-END:variables
}
