/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface.customer;

import ecosystem.Ecosystem;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import order.OrderDirectory;
import java.util.*;
import javax.swing.JFrame;
import order.Order;
import support.SupportRequest;
import support.SupportRequestDirectory;
import user_interface.customer.CustomerMainPanel;

/**
 *
 * @author nishu
 */
public class PastOrdersPanel extends javax.swing.JPanel {
    
    Ecosystem system;
    OrderDirectory ord;
    SupportRequestDirectory srd;
    String timeStamp;
    static int index;
    
    DefaultTableModel tblmodel;

    /**
     * Creates new form PastOrdersPanel
     */
    public PastOrdersPanel(Ecosystem system, OrderDirectory ord) {
        initComponents();
        this.system = system;
        this.ord  = ord;
        tblmodel = (DefaultTableModel)tblPastOrders.getModel();
        ord = system.getOrderDirectory();
                
         for(int i=0; i< ord.getOrderList().size(); i++)
        {
             Object data_value [] = {ord.getOrderList().get(i).getOrderid(),
                 
                 ord.getOrderList().get(i).getTotal_price(),
                 
                  timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date()),
                 
                 ord.getOrderList().get(i).getStatus()
                 
                 
                 

            };
           tblmodel.addRow(data_value);
        }
//        reasonDropDown = new javax.swing.JComboBox<>();
//        jPanel1.setBackground(new Color(0,0,0,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPastOrders = new javax.swing.JTable();
        btnCancelOrder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        tblPastOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Total Price", "Date", "Status"
            }
        ));
        tblPastOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPastOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPastOrders);

        btnCancelOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        jLabel2.setText("Raise Issue");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food Quality", "Order not delivered", "Item missing"}));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(btnCancelOrder)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelOrder)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1040, 710);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop-bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1042, 714);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPastOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPastOrdersMouseClicked
        // TODO add your handling code here:
        
        index = tblPastOrders.getSelectedRow();
        
    }//GEN-LAST:event_tblPastOrdersMouseClicked

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        // TODO add your handling code here:
        
        ord = system.getOrderDirectory();
        for(Order o1: ord.getOrderList())
        {
            if(o1.getOrderid().equals(tblPastOrders.getValueAt(index, 0).toString()))
            {
                o1.setStatus("Cancelled");
            }
            
            JOptionPane.showMessageDialog(new JFrame(), "Order cancelled");
            
        }
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ord = system.getOrderDirectory();
        srd = system.getSupportDirectory();
        for(Order o1: ord.getOrderList())
        {
            if(o1.getOrderid().equals(tblPastOrders.getValueAt(index, 0).toString()))
            {
                SupportRequest sr = srd.createReq(CustomerMainPanel.cust_id, o1.getOrderid(), jComboBox1.getSelectedItem().toString());
                srd.setSupList(sr);
                o1.setStatus("Issue raised");
            }
            
            JOptionPane.showMessageDialog(new JFrame(), "Support ticket raised");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private javax.swing.JComboBox<String> reasonDropDown;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPastOrders;
    // End of variables declaration//GEN-END:variables
}
