/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface.customer;

import java.awt.CardLayout;
import java.awt.Color;
import ecosystem.Ecosystem;
import javax.swing.table.DefaultTableModel;
import organisation.FoodVendorDirectory;
import organisation.FoodVendorOnboarding;
import items.ItemDirectory;
import items.Item;
import static user_interface_foodAdmin.foodAdminMainPanel.foodShopTable;
import cart.CartDirectory;


/**
 *
 * @author nishu
 */
public class ShopListPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodPanel
     */
    String shopType;
    Ecosystem system;
    FoodVendorDirectory fvd;
    ItemDirectory id;
    CartDirectory crd;
    
    DefaultTableModel tblModel;
    static int index;
    
    public ShopListPanel(Ecosystem system, String shop, CartDirectory crd) {
        initComponents();
        this.shopType = shop;
        this.system = system;
        this.crd = crd;
                
        fvd = system.getFoodDirectory();
        
        if(shop.equals("food"))
        {
            
        tblModel = (DefaultTableModel)tblShopDetails.getModel();
        tblModel.setRowCount(0);
      
         for(int i=0; i< fvd.getFoodVendorList().size(); i++)
        {
             Object data_value [] = {fvd.getFoodVendorList().get(i).getShop_id(),
                 
                 fvd.getFoodVendorList().get(i).getShop_name(),
                 
                 fvd.getFoodVendorList().get(i).getLocation()

            };
           tblModel.addRow(data_value);
        }
        }

        
  
        jPanel1.setBackground(new Color(0,0,0,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShopDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        tblShopDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Shop Id", "Shop Name", "Location"
            }
        ));
        tblShopDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShopDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShopDetails);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 710);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop-bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1042, 714);

        container.setLayout(new java.awt.CardLayout());
        add(container);
        container.setBounds(0, 0, 1042, 714);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop-bg.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1042, 714);
    }// </editor-fold>//GEN-END:initComponents

    private void tblShopDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShopDetailsMouseClicked
        // TODO add your handling code here:
        if(shopType.equals("food")){
            jPanel1.setVisible(false);
            jLabel1.setVisible(false);
            index = tblShopDetails.getSelectedRow();
            FoodItemsPanel fooditemsPanel = new FoodItemsPanel(system, index, crd);
            container.add("workArea",fooditemsPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);       
            container.setVisible(true);
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foodAdmin.png"))); 

            
            
            
            
            
            
        }
        
        
        
        else if(shopType.equals("grocery")){
            jPanel1.setVisible(false);
            jLabel1.setVisible(false);
            GroceryItemsPanel groceryitemsPanel = new GroceryItemsPanel();
            container.add("workArea",groceryitemsPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);       
            container.setVisible(true);
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grocerieAdmin.jpeg")));
        }else if(shopType.equals("meat")){
            jPanel1.setVisible(false);
            jLabel1.setVisible(false);
            MeatItemsPanel meatitemsPanel = new MeatItemsPanel();
            container.add("workArea",meatitemsPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);       
            container.setVisible(true);
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MeatAdmin.png")));       
        }
        else{
            jPanel1.setVisible(false);
            jLabel1.setVisible(false);
            PharmaItemsPanel pharmaitemsPanel = new PharmaItemsPanel();
            container.add("workArea",pharmaitemsPanel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);       
            container.setVisible(true);
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pharamaadmin_1200x720.png")));
        }
    }//GEN-LAST:event_tblShopDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblShopDetails;
    // End of variables declaration//GEN-END:variables
}
