/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface_sysadmin;

//import community.Community;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import ecosystem.Ecosystem;
import enterprise.Enterprise;
import enterprise.EnterpriseDirectory;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author snehagovindarajan
 */
public class communityPanel extends javax.swing.JPanel {

    /**
     * Creates new form networkPanel
     */
    
    private Ecosystem system;
    public communityPanel() {
        
    }
    
 public communityPanel(Ecosystem system){
        this.system =  system;
        initComponents();
        networkPane.setBackground(new Color(0,0,0,30));
//        populateNetworkTable();
    }
    
    
//       private void populateNetworkTable() {
//        DefaultTableModel model = (DefaultTableModel) communityJTable.getModel();
//        model.setRowCount(0);
//        
//            for(int i=0;i< system.getCommunityList().size();i++){
//            Community community = system.getCommunityList().get(i);
//            model.addRow(new Object[]{
//                   community.getCommunityName(),
//                   community.getZipCode()
//            
//            });
//    }
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        communityJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        addCommunityName = new javax.swing.JTextField();
        communitySubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addCommunityCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        communityJTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        communityJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Zip Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(communityJTable);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name");

        addCommunityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommunityNameActionPerformed(evt);
            }
        });

        communitySubmit.setText("SUBMIT");
        communitySubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                communitySubmitMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Zip Code");

        addCommunityCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommunityCodeActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lao MN", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Add Community");

        javax.swing.GroupLayout networkPaneLayout = new javax.swing.GroupLayout(networkPane);
        networkPane.setLayout(networkPaneLayout);
        networkPaneLayout.setHorizontalGroup(
            networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPaneLayout.createSequentialGroup()
                .addGroup(networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(networkPaneLayout.createSequentialGroup()
                        .addGap(486, 486, 486)
                        .addComponent(communitySubmit))
                    .addGroup(networkPaneLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(86, 86, 86)
                        .addGroup(networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCommunityCode, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(networkPaneLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(networkPaneLayout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        networkPaneLayout.setVerticalGroup(
            networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPaneLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCommunityCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(communitySubmit)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        add(networkPane);
        networkPane.setBounds(-90, 0, 1210, 720);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee_background_1200x720.jpeg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void addCommunityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommunityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCommunityNameActionPerformed

    private void communitySubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_communitySubmitMouseClicked
        // TODO add your handling code here:
                if(addCommunityName.getText().trim().equals("")){
                     JOptionPane.showMessageDialog(new JFrame(), "Enter valid Community Name..!!");
                }else if(addCommunityCode.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(new JFrame(), "Enter valid Zipcode ..!!");
                }
                else{
                String name = addCommunityName.getText().trim();
                int zipcode = Integer.parseInt(addCommunityCode.getText());
//        if (!name.isEmpty()) {
//            if (system.isUnique(name)) {
                 
//                Community community = system.createAndAddNetwork();
//                community.setCommunityName(name);
//                community.setZipCode(zipcode);
//                community.setEnterpriseDirectory(new EnterpriseDirectory());
                JOptionPane.showMessageDialog(null, "Network Successfully Created");
                addCommunityName.setText("");
                addCommunityCode.setText("");
//            } else {
//                JOptionPane.showMessageDialog(null, "Network Already Exits");
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Enter network name");
//        }
//        populateNetworkTable();
         }
        
        
    }//GEN-LAST:event_communitySubmitMouseClicked

    private void addCommunityCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommunityCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCommunityCodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addCommunityCode;
    private javax.swing.JTextField addCommunityName;
    private javax.swing.JTable communityJTable;
    private javax.swing.JButton communitySubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel networkPane;
    // End of variables declaration//GEN-END:variables
}
