/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface_dataAnalyst;

import cart.Cart;
import cart.CartDirectory;
import user_interface.employee_admin.*;
import db4util.Db4util;
import ecosystem.Ecosystem;
import java.awt.Color;
import javax.swing.JFrame;
import user_interface.MainJFrame;
import employee.Employee;
import employee.EmployeeAccountDirectory;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import order.Order;
import order.OrderDirectory;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author nishu
 */
public class DataAnalysis extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeAdminPanel
     */
    
    Ecosystem system;
    MainJFrame mainframe;
    EmployeeAccountDirectory emp_dir_ob; 
    CartDirectory cartDir;
    Employee emp_ob;
    int employeeIndex;
    private Db4util dB4OUtil = Db4util.getInstance();
    DefaultTableModel tblmodel;
    
    
    public DataAnalysis(Ecosystem system, MainJFrame mainframe) {
        initComponents();
        this.system = system;
        this.mainframe = mainframe;
        System.out.println("EmployeeAdmin");
        emp_dir_ob = system.getEmpDirectory();
       // orderDir = system.getOrderDirectory();
       cartDir = system.getCartDirectory();
      
      
                
        jPanel1.setBackground(new Color(0,0,0,15));
        
        for(Cart C: cartDir.getCartList())
        {
            System.out.println(C.getType());
        }
    }
    private void drawchart(){
        DefaultPieDataset pieDataset= new DefaultPieDataset();
        EmployeeAccountDirectory empList = system.getEmpDirectory();
         Map<String, Integer> hMap = new HashMap<>();


        for (Employee employee : empList.getEmpAccountList()) {
        if( hMap.get(employee.getRole())==null)
        {
              hMap.put(employee.getRole(), 1);
        }else{
        hMap.put(employee.getRole(),hMap.get(employee.getRole())+1 );
        }
            
        }
        for (Map.Entry<String,Integer> entry : hMap.entrySet()) 
            pieDataset.setValue(entry.getKey(),entry.getValue());          
             
        JFreeChart chart=ChartFactory.createPieChart("Employee ROLE", pieDataset);
        PiePlot p=(PiePlot)chart.getPlot();
        ChartPanel chartPanel= new ChartPanel(chart);
      
        ChartFrame frame= new ChartFrame("Employee ROLE",chart);
           frame.setVisible(true);
           frame.setSize(450,500);
    }
    
  
    
        private void drawchartOrder(){
        DefaultPieDataset pieDataset= new DefaultPieDataset();
        cartDir = system.getCartDirectory();
         Map<String, Integer> hMap = new HashMap<>();


        for (Cart cart :cartDir.getCartList()) {
        if( hMap.get(cart.getType())==null)
        {
              hMap.put(cart.getType(), 1);
        }else{
        hMap.put(cart.getType(),hMap.get(cart.getType())+1 );
        }
            
        }
        for (Map.Entry<String,Integer> entry : hMap.entrySet()) 
            pieDataset.setValue(entry.getKey(),entry.getValue());          
             
        JFreeChart chart=ChartFactory.createPieChart("Cart Items", pieDataset);
        PiePlot p=(PiePlot)chart.getPlot();
        ChartPanel chartPanel= new ChartPanel(chart);
      
        ChartFrame frame= new ChartFrame("Cart Items",chart);
           frame.setVisible(true);
           frame.setSize(450,500);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        reportBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel10.setFont(new java.awt.Font("Maku", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Welcome Admin ..!!");

        reportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empAnalyst.jpeg"))); // NOI18N
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart-report.jpeg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 2, 18)); // NOI18N
        jLabel4.setText("Employee Report");

        jLabel5.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 2, 18)); // NOI18N
        jLabel5.setText("Order Report");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reportBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(170, 170, 170))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(200, 200, 200))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reportBtn)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(39, 39, 39))
        );

        add(jPanel1);
        jPanel1.setBounds(60, 50, 950, 560);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-square-shape-bg.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
        drawchart();
    }//GEN-LAST:event_reportBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        drawchartOrder();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainframe.logoutAction();
        mainframe.displayPane();
    }//GEN-LAST:event_jButton2ActionPerformed
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reportBtn;
    // End of variables declaration//GEN-END:variables
}
