/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface.delivery_admin;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author nishu
 */
public class DeliveryAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryAdminPanel
     */
    public DeliveryAdminPanel() {
        initComponents();
        jPanel1.setBackground(new Color(0, 0, 0, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDeliveryAdmin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        tblDeliveryAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer ID", "Items", "Address", "Status"
            }
        ));
        tblDeliveryAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeliveryAdminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDeliveryAdmin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );

        add(jPanel1);
        jPanel1.setBounds(80, 40, 1040, 630);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-square-shape-bg.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDeliveryAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeliveryAdminMouseClicked
        // TODO add your handling code here:
        String message = "\n";
        Object[] params = {message};
        JOptionPane.showConfirmDialog(null, params, "Assign Delivery Person", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_tblDeliveryAdminMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDeliveryAdmin;
    // End of variables declaration//GEN-END:variables
}



